import { NextResponse } from "next/server";
import { getServerSession } from "next-auth";
import { authOptions } from "@/lib/auth";
import { connectDB } from "@/lib/mongodb";
import User from "@/models/User";
import IDCardTemplate from "@/models/IDCardTemplate";
import Batch from "@/models/Batch";

/**
 * @route   GET /api/v1/student/id-card
 * @desc    Fetch student data and default ID card template for digital rendering
 */
export async function GET(req) {
    try {
        const session = await getServerSession(authOptions);
        if (!session || session.user.role !== 'student') {
            return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
        }

        await connectDB();

        // 1. Fetch Student Data with Institute and Batch info
        const student = await User.findById(session.user.id)
            .populate('institute')
            .lean();

        if (!student) {
            return NextResponse.json({ error: "Student not found" }, { status: 404 });
        }

        // 2. Find the latest generated ID card
        const StudentIDCard = (await import("@/models/StudentIDCard")).default;
        const generatedCard = await StudentIDCard.findOne({
            studentId: session.user.id,
            status: 'ACTIVE'
        }).sort({ createdAt: -1 }).lean();

        if (!generatedCard) {
            return NextResponse.json({ error: "ID Card not yet generated by administrator" }, { status: 404 });
        }

        return NextResponse.json({
            student: {
                fullName: student.fullName,
                grNumber: student.grNumber,
                enrollmentNumber: student.enrollmentNumber,
            },
            generatedCard: {
                frontImage: generatedCard.frontImageUrl,
                backImage: generatedCard.backImageUrl,
                generatedAt: generatedCard.createdAt
            }
        });

    } catch (error) {
        console.error("Student ID Card API Error:", error);
        return NextResponse.json({ error: "Internal server error" }, { status: 500 });
    }
}
